#!/bin/bash

md5sc()
{
    local target="$1"
    local checksumString=$(md5sum "$target")
    local checksum=${checksumString:0:32}
    echo "$checksum" > "$target.md5"
    echo "$checksum $target"
}

if [ "$#" -ne 1 ]; then
    echo "gzipit: Creates a gzip file from the file specified, after first creating an MD5 side-car file from the file specified."
    echo "Usage: gzipit somefilehere"
else
    md5sc "$1"
    gzip -9cv --rsyncable "$1" > "$1".gz
fi

