#!/bin/bash
#vericp
#Copies a file and verifies the transfer completed with no corrupted data using md5 checksum comparison.

md5sc()
{
    local target="$1"
    local checksumString=$(md5sum "$target")
    local checksum=${checksumString:0:32}
    echo "$checksum" > "$target.md5"
    echo "$checksum $target"
}

md5v()
{
    target="$1"
    targetNameLength=${#target}
    let targetNameLength-=4
    targetExtension=${target:targetNameLength:4}

    controlChecksum=0 #checksum in sidecar file
    testChecksumTarget=0 #file to create checksum from
    if [ "$targetExtension" == ".md5" ]; then
	    controlChecksum=$(cat "$target")
	    controlChecksum=${controlChecksum:0:32}
	    testChecksumTarget=${target:0:targetNameLength}
    else
	    controlChecksum=$(cat "$target.md5")
	    controlChecksum=${controlChecksum:0:32}
	    testChecksumTarget="$target"
    fi

    testChecksum=0 #checksum of file we're verifying
    if [ -e "$testChecksumTarget" ] && [ "$controlChecksum" != "" ]; then
	    testChecksumString=$(md5sum "$testChecksumTarget")
	    testChecksum=${testChecksumString:0:32}
	    if [ "$controlChecksum" == "$testChecksum" ]; then
		    echo "Control: $controlChecksum"
		    echo "Test   : $testChecksum"
		    echo "$testChecksumTarget passed verification!"
		    return 0;
	    else
		    echo "Control: $controlChecksum"
		    echo "Test   : $testChecksum"
		    echo "$testChecksumTarget FAILED verification!"
		    return 1;
	    fi
    else
	    echo "Sidecar or target file missing or unreadable."
    fi
}

#here we actually need to do the copying and verifying.